version: "3.3"

services:
  zookeeper-node-01:
    image: zookeeper
    container_name: zookeeper-node-01
    ports:
      - "2181:2181"
      - "2182:2182"
    networks:
      - clickhouse-cluster
  clickhouse-node-01:
    image: yandex/clickhouse-server
    container_name: clickhouse-node-01
    volumes:
      - ./config/node-01-config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9363:9363"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-cluster
    depends_on:
      - zookeeper-node-01
  clickhouse-node-02:
    image: yandex/clickhouse-server
    container_name: clickhouse-node-02
    volumes:
      - ./config/node-02-config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "9001:9000"
      - "8124:8123"
      - "9364:9363"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-cluster
    depends_on:
      - zookeeper-node-01
  clickhouse-node-03:
    image: yandex/clickhouse-server
    container_name: clickhouse-node-03
    volumes:
      - ./config/node-03-config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "9002:9000"
      - "8125:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-cluster
    depends_on:
      - zookeeper-node-01
  clickhouse-node-04:
    image: yandex/clickhouse-server
    container_name: clickhouse-node-04
    volumes:
      - ./config/node-04-config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "9003:9000"
      - "8126:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-cluster
    depends_on:
      - zookeeper-node-01
  clickhouse-php-client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: clickhouse-php-client
    networks:
      - clickhouse-cluster
networks:
  clickhouse-cluster:
    driver: bridge
